services:
  stats-server:
    build: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server
      - SPRING_DATASOURCE_USERNAME=stats-server
      - SPRING_DATASOURCE_PASSWORD=stats-server

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stats-server
      - POSTGRES_USER=stats-server
      - POSTGRES_DB=stats-server
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/ewm-service
      - SPRING_DATASOURCE_USERNAME=ewm-service
      - SPRING_DATASOURCE_PASSWORD=ewm-service

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6543:5433"
    environment:
      - POSTGRES_PASSWORD=ewm-service
      - POSTGRES_USER=ewm-service
      - POSTGRES_DB=ewm-service
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
